#pragma once

#include "operations/adc.h"
// #include "operations/and.h"
// #include "operations/asl.h"
// #include "operations/bcc.h"
// #include "operations/bcs.h"
// #include "operations/beq.h"
// #include "operations/bit.h"
// #include "operations/bmi.h"
// #include "operations/bne.h"
// #include "operations/bpl.h"
#include "operations/brk.h"
// #include "operations/bvc.h"
// #include "operations/bvs.h"
// #include "operations/clc.h"
// #include "operations/cld.h"
// #include "operations/cli.h"
// #include "operations/clv.h"
// #include "operations/cmp.h"
// #include "operations/cpx.h"
// #include "operations/cpy.h"
// #include "operations/dec.h"
// #include "operations/dex.h"
// #include "operations/dey.h"
// #include "operations/eor.h"
// #include "operations/inc.h"
// #include "operations/inx.h"
// #include "operations/iny.h"
// #include "operations/jmp.h"
// #include "operations/jsr.h"
// #include "operations/lda.h"
// #include "operations/ldx.h"
// #include "operations/ldy.h"
// #include "operations/lsr.h"
#include "operations/nop.h"
// #include "operations/ora.h"
// #include "operations/pha.h"
// #include "operations/php.h"
// #include "operations/pla.h"
// #include "operations/plp.h"
// #include "operations/rol.h"
// #include "operations/ror.h"
// #include "operations/rti.h"
// #include "operations/rts.h"
// #include "operations/sbc.h"
// #include "operations/sec.h"
// #include "operations/sed.h"
// #include "operations/sei.h"
// #include "operations/sta.h"
// #include "operations/stx.h"
// #include "operations/sty.h"
// #include "operations/tax.h"
// #include "operations/tay.h"
// #include "operations/tsx.h"
// #include "operations/txa.h"
// #include "operations/txs.h"
// #include "operations/tya.h"
